In [2]:
import pandas as pd

In [3]:
ratings=pd.read_csv("/cluster_analysis.csv")

In [12]:
ratings

Feature_1  Feature_2
0     2.248357   1.930868
1     2.323844   2.761515
2     1.882923   1.882932
3     2.789606   2.383717
4     1.765263   2.271280
..         ...        ...
295   5.035783   0.761171
296   5.239490   1.166831
297   5.518770   0.744992
298   4.865063   0.510618
299   4.777853   1.188650

[300 rows x 2 columns]

In [10]:
type(ratings)

pandas.core.frame.DataFrame

In [15]:
ratings['Feature_1']


0      2.248357
1      2.323844
2      1.882923
3      2.789606
4      1.765263
         ...   
295    5.035783
296    5.239490
297    5.518770
298    4.865063
299    4.777853
Name: Feature_1, Length: 300, dtype: float64

In [28]:
titles=['Feature_1','Feature_2']

In [29]:
titles

['Feature_1', 'Feature_2']

In [30]:
movies=pd.DataFrame(ratings, columns=titles)

In [31]:
movies

Feature_1  Feature_2
0     2.248357   1.930868
1     2.323844   2.761515
2     1.882923   1.882932
3     2.789606   2.383717
4     1.765263   2.271280
..         ...        ...
295   5.035783   0.761171
296   5.239490   1.166831
297   5.518770   0.744992
298   4.865063   0.510618
299   4.777853   1.188650

[300 rows x 2 columns]

In [32]:
from sklearn import cluster

In [50]:
data = movies


In [51]:
data

Feature_1  Feature_2
0     2.248357   1.930868
1     2.323844   2.761515
2     1.882923   1.882932
3     2.789606   2.383717
4     1.765263   2.271280
..         ...        ...
295   5.035783   0.761171
296   5.239490   1.166831
297   5.518770   0.744992
298   4.865063   0.510618
299   4.777853   1.188650

[300 rows x 2 columns]

In [52]:
k_means=cluster.KMeans(n_clusters=2, max_iter=100, random_state=1)

In [53]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [54]:
k_means.fit(data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [55]:
labels=k_means.labels_

In [56]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

In [57]:
movies

Feature_1  Feature_2
0     2.248357   1.930868
1     2.323844   2.761515
2     1.882923   1.882932
3     2.789606   2.383717
4     1.765263   2.271280
..         ...        ...
295   5.035783   0.761171
296   5.239490   1.166831
297   5.518770   0.744992
298   4.865063   0.510618
299   4.777853   1.188650

[300 rows x 2 columns]

In [81]:
outcome = pd.DataFrame({'Feature_1': movies['Feature_1'], 'Feature_2': movies['Feature_2'], 'Cluster ID': labels})


In [82]:
outcome

Feature_1  Feature_2  Cluster ID
0     2.248357   1.930868           0
1     2.323844   2.761515           0
2     1.882923   1.882932           0
3     2.789606   2.383717           0
4     1.765263   2.271280           0
..         ...        ...         ...
295   5.035783   0.761171           0
296   5.239490   1.166831           0
297   5.518770   0.744992           0
298   4.865063   0.510618           0
299   4.777853   1.188650           0

[300 rows x 3 columns]

In [83]:
k_means.cluster_centers_

array([[3.45984959, 1.47693741],
       [8.06412436, 8.02174382]])

In [107]:
import numpy as np


In [116]:
file_path = "cluster_analysis.csv"
cluster_analysis = pd.read_csv("/cluster_analysis.csv")

# Extract Feature_1 and Feature_2 values
feature_1_values = cluster_analysis['Feature_1'].values
feature_2_values = cluster_analysis['Feature_2'].values

# Create the testData array
testData = np.column_stack((feature_1_values, feature_2_values))

# Display the testData
print(testData)




[[ 2.24835708  1.93086785]
 [ 2.32384427  2.76151493]
 [ 1.88292331  1.88293152]
 [ 2.78960641  2.38371736]
 [ 1.76526281  2.27128002]
 [ 1.76829115  1.76713512]
 [ 2.12098114  1.04335988]
 [ 1.13754108  1.71885624]
 [ 1.49358444  2.15712367]
 [ 1.54598796  1.29384815]
 [ 2.73282438  1.88711185]
 [ 2.0337641   1.28762591]
 [ 1.72780864  2.0554613 ]
 [ 1.42450321  2.18784901]
 [ 1.69968066  1.85415313]
 [ 1.69914669  2.92613909]
 [ 1.99325139  1.47114454]
 [ 2.41127246  1.38957818]
 [ 2.1044318   1.02016494]
 [ 1.33590698  2.09843062]
 [ 2.36923329  2.08568414]
 [ 1.94217586  1.84944815]
 [ 1.26073901  1.6400779 ]
 [ 1.76968061  2.52856111]
 [ 2.17180915  1.11847992]
 [ 2.16204199  1.80745886]
 [ 1.661539    2.30583814]
 [ 2.51549976  2.46564006]
 [ 1.58039124  1.84539381]
 [ 2.16563172  2.48777256]
 [ 1.76041288  1.90717051]
 [ 1.44683251  1.40189669]
 [ 2.40626291  2.67812001]
 [ 1.96399494  2.50176645]
 [ 2.18081801  1.67744012]
 [ 2.1806978   2.76901828]
 [ 1.98208698  2.78232183]
 

In [117]:
testData

array([[ 2.24835708,  1.93086785],
       [ 2.32384427,  2.76151493],
       [ 1.88292331,  1.88293152],
       [ 2.78960641,  2.38371736],
       [ 1.76526281,  2.27128002],
       [ 1.76829115,  1.76713512],
       [ 2.12098114,  1.04335988],
       [ 1.13754108,  1.71885624],
       [ 1.49358444,  2.15712367],
       [ 1.54598796,  1.29384815],
       [ 2.73282438,  1.88711185],
       [ 2.0337641 ,  1.28762591],
       [ 1.72780864,  2.0554613 ],
       [ 1.42450321,  2.18784901],
       [ 1.69968066,  1.85415313],
       [ 1.69914669,  2.92613909],
       [ 1.99325139,  1.47114454],
       [ 2.41127246,  1.38957818],
       [ 2.1044318 ,  1.02016494],
       [ 1.33590698,  2.09843062],
       [ 2.36923329,  2.08568414],
       [ 1.94217586,  1.84944815],
       [ 1.26073901,  1.6400779 ],
       [ 1.76968061,  2.52856111],
       [ 2.17180915,  1.11847992],
       [ 2.16204199,  1.80745886],
       [ 1.661539  ,  2.30583814],
       [ 2.51549976,  2.46564006],
       [ 1.58039124,

In [118]:
type(testData)

numpy.ndarray

In [119]:
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [120]:
labels_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

In [121]:
userNames=np.array(['Feature_1','Feature_2']).reshape(-1,1)

In [122]:
userNames

array([['Feature_1'],
       ['Feature_2']], dtype='<U9')

In [123]:
userNames.reshape(-1,1)

array([['Feature_1'],
       ['Feature_2']], dtype='<U9')

In [124]:
userNames

array([['Feature_1'],
       ['Feature_2']], dtype='<U9')

In [126]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], d

In [127]:
labels_test=labels_test.reshape(-1,1)

In [128]:
labels_test

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [129]:
cols=movies.columns.tolist()

In [130]:
cols

['Feature_1', 'Feature_2']

In [131]:
cols.append('Cluster ID')

In [132]:
cols

['Feature_1', 'Feature_2', 'Cluster ID']